#!/bin/bash

docker stop vscode
docker rm vscode

docker run \
  --env WAYLAND_DISPLAY=$WAYLAND_DISPLAY \
  --env XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR \
  --volume $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR \
  --env DISPLAY=$DISPLAY \
  --volume /tmp/.X11-unix:/tmp/.X11-unix \
  --device /dev/dri \
  --volume /home/user/university:/root/university \
  --name "vscode" \
  vscode 
