background_opacity 0.80
# Set the font family and size
font_family	JetBrains Mono Nerd
font_size        13.0

single_window_padding_width 10
placement_strategy top-left


# Enable anti-aliasing (smooth fonts)
enable_font_antialiasing yes
allow_remote_control yes

background #090708 
foreground #FFFFFF

# Black
color0 #090708
# Red
color1 #FF9088
# Green
color2 #8DEA2D
# Yellow
color3 #FEF29C
# Blue
color4 #B1DEFA
# Magenta
color5 #EB7FB2
# Cyan
color6 #6A9FBA
# White
color7 #FFFFFF

# Black
color8 #090708
# Red
color9 #FF9088
# Green
color10 #8DEA2D
# Yellow
color11 #FEF29C
# Blue
color12 #B1DEFA
# Magenta
color13 #EB7FB2
# Cyan
color14 #6A9FBA
# White
color15 #FFFFFF
